export const playlists = [
    {
        name: 'Nomad Label',
        curator: '@hen_radio',
        description: 'Various Nomad_label sound objkts',
        img: '/images/nomad_label.png',
        slug: 'nomad-label',
        tracks: [
            {
                'id': 98380, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #00',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmQCSnBGmQoKNC43kddTqdNWJXM2nEiEf6zXJd88T8Wqex',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmRzzN8NmeiB7KhjhzQiEyG4aUnkrb92JCZZDDYkvhL7DS', 'tags': [],
            },
            {
                'id': 99466, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #01',
                'src': 'https://dweb.link/ipfs/QmNn5PQyDRfLQ9HYQiFhd8ikQTQnRpe3NQ3wMVsjoKo4LW',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmRH9rf5N3nXE6U8iV6z8Fd56g2mqfc9DNMGwrVGV7F2ZN', 'tags': [],
            },
            {
                'id': 100843, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #02',
                'src': 'https://ipfs.io/ipfs/QmdSgdkusmiKea2u4PzESaipZKbttpo48s7tYp5i63j3BD',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmYKkQi4V26o4MHtTSgcdvjePuh8S7hrnpyj4gBcFY4r8i', 'tags': [],
            },
            {
                'id': 100943, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #03',
                'src': 'https://ipfs.io/ipfs/QmRwbLVhnXFKqHz1trzpxWzE6QtNqxWkppM7pb7JNHtzHD',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://Qmctv8KjqBGyqN6gQ7Ap22Y8cTaJ1g1NqZLbC14DG5b3TW', 'tags': [],
            },
            {
                'id': 101079, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #04',
                'src': 'https://ipfs.io/ipfs/QmatzMuSP2XAWDMpjUxmXeFDCSJAtePjhte7J58DE4ssKp',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmdrM9XZELeuf4dqfCWCqmWonS7znSyGsEA512Dbo143k3', 'tags': [],
            },
            {
                'id': 194594, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'cryptochristo - ode to joy tape speed distortion',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmXSBbFHKAu9eYjhpqZdugWGEgy4j2DeD5AJbK3uPvwArK',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmTDJ48ECcMV8va1CWSjhhqzD7vVdsDMweqVLfukjQDMeQ', 'tags': [],
            },
            {
                'id': 195042, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'Tua Tempestade',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmNsxddw4A9QqwxppQKaBqBNUkAha3kg8rG4tgESjFAT4w',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmaSsNYYbWFgKwvxF3LqR8YzJ4zCKDKjKyBfcaNBYgMrBU', 'tags': [],
            },
            {
                'id': 195568, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'Fierce and Fabulosa - work in process',
                'src': 'https://dweb.link/ipfs/QmVknbTerGiHF3T4wFsXWFRAQWr1eWMmXFC4TUnCV974CB',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmZQmmNEY1jG1xdqvy5Z3udwGRrRRfeZ7wZWZkWYNF6XDZ', 'tags': [],
            },
            {
                'id': 199974, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'STE-002[undefined].mp3 - 1hz estúdio',
                'src': 'https://infura-ipfs.io/ipfs/QmeeD6f1dUvLio7Hn49DuRVMJgo8L867ACXvr9rufQsD9Y',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmVKNQxqmi2s9E4TbmRjVu7FB5aL5PGcQZ2BibvV3mii8F', 'tags': [],
            },
            {
                'id': 200478, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'Pire(กองฟืน) - pradit-saengkrai(thailand)',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmU292s8BdY1Mr16T1bQEbSYqoUcWXg5sWsiZVrYc78CPw',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmRzpk3hFBZQfzzm2YYBowxdvDzrHfkTVkvGRrRFRzTKFu', 'tags': [],
            }],
    },
    {
        name: 'We love Marcello, dead or not',
        curator: '@hen_radio',
        description: 'Agreeable sound experiments',
        img: '/images/dead_marcello.png',
        slug: 'we-love-marcello-dead-or-not',
        tracks: [
            {
                'id': 162790, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'Krell Phrygian G',
                'src': 'https://ipfs.io/ipfs/QmXfnkWRwuTE5UbK6FAXfLR1BAiU93SeMo7qEcFoVzHDGE',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmRXXRdwAyjCNBKxZr3HDMKJLEVFjUjtPTbYrMz9PUBQwE', 'tags': [],
            },
            {
                'id': 178113, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'Machines by Alan Turing',
                'src': 'https://dweb.link/ipfs/QmepYpPzTsqNeArvSydhqDbWE3TZ6RsGV54hWMCGS6zqQD',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://Qmbbntf1xKKiTkhWBncDYmuHwK3i1sTEbeaAgsP1fVAL6g', 'tags': [],
            },
            {
                'id': 189702, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'morning path 5',
                'src': 'https://gateway.pinata.cloud/ipfs/QmZ4Txv4jHsekCpdC7V7fiEpFMFgSCCqNJPrYgFYUwNoJ6',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmeGnUqLXyaDJ5R75ZjQNfyrBdPBgF9xXhEaun4WY9PsyA', 'tags': [],
            },
            {
                'id': 197596, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'ao Sol',
                'src': 'https://dweb.link/ipfs/QmNaoRpbfzZGGwjDdE3VYj9UVne8a47Mj3tabGq5QuNZ9K',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmQVoWd1Rhm4AwstTmZEZrEbV9eYd5nT5dpT29QbZGZmUg', 'tags': [],
            }],
    },
    {
        name: 'Tezos-Artcast Mix Tape #1',
        curator: '@ArtcastTezos',
        description: 'Tezos-artcast mixtape A: Sonic explorations in a time of strangeness.',
        img: '/images/tezos-artcast-mix-tape-1.png',
        slug: 'tezos-artcast-mix-tape-1',
        tracks: [
            {
                id: 40382, creator: {
                    walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX', name: '',
                    metadata: {},
                }, title: 'The Portal',
                src: 'https://dweb.link/ipfs/QmWRJpiSnDcu76NvUq9CkY1U2cVaP8Z75G3nArnqbQ1eGa',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmcisSaejao4ii7K4BtrZSGPCnN7tDZSW3Et7yrcdWRPjb', tags: [],
            },
            {
                id: 43421, creator: {
                    walletAddress: 'tz1YvJvemXC2tGoHNMizpJTLpMDsUrKbhwVY', name: 'DREAMZ',
                    metadata: {description: ''},
                }, title: 'The Official Hic et nunc Song (full version) ',
                src: 'https://dweb.link/ipfs/QmPBtLgYtAkKYg6C1vv8wUWFM5R6Eza2TNa7nyPbjWAQGM',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://Qme3r93omWizSM9Qa4Du1fAfJxK624nTwFd575pKLQx4Q7', tags: [],
            },
            {
                id: 44528, creator: {
                    walletAddress: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp', name: '',
                    metadata: {},
                }, title: '|WOAH}C00L|',
                src: 'https://cloudflare-ipfs.com/ipfs/QmYRADeeCDWyayLm8jrePE7EzVo9NXTBgXSfpshQcMuCEm',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmbE6CEphzZhPhm2sm5WPhEqGdunZTnvo4HP1NLQSrP2Wh', tags: [],
            },
            {
                id: 160691, creator: {
                    walletAddress: 'tz1h8HEENKv32TSzTzS52STTZGrE2q7rnrDL',
                    name: 'luisoalquimista', metadata: {description: 'Alchemy of the sound.'},
                }, title: 'Maracá Power',
                src: 'https://gateway.pinata.cloud/ipfs/Qmd1GkL2v5y9NVUJKnN6iEnuY3WG7AoYzrFHL959qHTLtT',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmZA3pKKSmdm9afDms91rZyZeQmebpvkKyiAX7Z4gmFKoD', tags: [],
            },
            {
                id: 163778, creator: {
                    walletAddress: 'tz1irQgAEeS7BWGMAnidUv4Mq5QWis18q2qe', name: '',
                    metadata: {},
                }, title: 'Fuck La Rat Race (Limited Sketch Edition)',
                src: 'https://dweb.link/ipfs/QmU1wYCvyGa1Y7Fyf4bKUs8GumQLQbCoMQfZi96sthe194',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmYEf63DsPV8r3oTikLzPrLnWzfhvYYV51GnCUV9SgUZYR', tags: [],
            },
            {
                id: 164362, creator: {
                    walletAddress: 'tz1hnmpvKPDDnXfh9tkE2ouWG2rP3uaUVjC4', name: '',
                    metadata: {},
                }, title: 'Yars Rev (full song)',
                src: 'https://cloudflare-ipfs.com/ipfs/QmfEejtbBJfB5uvm82Epd4oAbfriFR5G3kuo4wBe32qeBN',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmYugWTXubAhCetQEcvZr6eBJc2Ntw1RZ3D4rEDr9dno6F', tags: [],
            },
            {
                id: 170082, creator: {
                    walletAddress: 'tz1QpFbzwU6XuiByAyL9Ny8EEWYs4VAfPJH2', name: '',
                    metadata: {},
                },
                title: '𝖉𝖎𝖌𝖎𝖙𝖆𝖑 𝖒𝖔𝖘𝖘 - 𝖂𝖊𝖑𝖈𝖔𝖒𝖊 𝖙𝖔 𝖙𝖍𝖊 𝕮𝖑𝖔𝖚𝖉 𝕮𝖎𝖙𝖞',
                src: 'https://dweb.link/ipfs/QmbGisy69VoLdec6d5YihxCZg42JURNnsjz52EnvM9nEro',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmaydxYS75aENSSmXBLa6hQ9eZwEsuCfEDqJkvV3XPjzvA', tags: [],
            },
            {
                id: 171608, creator: {
                    walletAddress: 'tz1ae2d1BJt7YUqaaec6Xenh3mBqS7VjSZtK', name: 'Yoeshi Labs',
                    metadata: {
                        identicon: 'ipfs://QmPddzzzfjDcxvZH6LmNDEBo8FYZQFSrNNA7fkf2m9m5jV',
                        description: 'Music - Art - Support',
                    },
                }, title: 'Pumpin\' - Yoeshi Labs Ft. Seb & SPP',
                src: 'https://infura-ipfs.io/ipfs/QmbFfWKYHVMULKLyiJ5v1rjXEPqw1vMJdgsGeC2DJR6QqY',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmR5yn7dRGYNYp5ytsa6xmyvSqEScYtgE7mvYisCcjWbys', tags: [],
            },
            {
                id: 175354, creator: {
                    walletAddress: 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', name: 'dead_marcelo',
                    metadata: {description: '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, title: 'weaving webꜩ hen200',
                src: 'https://cloudflare-ipfs.com/ipfs/QmW6nNEFyodikvGVoZPzPGQVvefnwXm4W9ongmF5cmxikn',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmUrJdRc4Xecf6nFGg5cRqLP5VcNoGDqQYTa3KwLP27Zpx', tags: [],
            },
            {
                id: 176366, creator: {
                    walletAddress: 'tz1h5hcKNHceWHkezg9DjXqxBDXhDWn1EYjR', name: 'ABroJo Music',
                    metadata: {
                        identicon: 'ipfs://QmeF5wd4mLQQrVu5zp22X4ZLv4zZ4A8KcKQz42GULeynMo',
                        description: 'is Pablo Bersier\'s solo musical project. Electronic music producer for 25 years from Patagonia.',
                    },
                }, title: 'Dawn on Titan',
                src: 'https://dweb.link/ipfs/QmeWGwK7nV12kX12CQT3pD2tKqjxFbWYitcmJudj9EH74w',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmZnJoq7uhqFgQfoYrdEF73G3MwwGvEqGJQBv91tRY4n9G', tags: [],
            },
            {
                id: 176431, creator: {
                    walletAddress: 'tz2GP2o3kMJ8Q22FdjBo6QeheqUTAyEkHBo4', name: 'Marc Fendel',
                    metadata: {description: ''},
                }, title: 'Circular Data Remix',
                src: 'https://cloudflare-ipfs.com/ipfs/QmeqZza3NKH1STaes5934Hssru5uBvPpwHzhfvYVRpk4is',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmUSvwetYPTX6w9bfx26qMkP6bE6LBo4zZsbkw7dEyipGa', tags: [],
            },
            {
                id: 176756, creator: {
                    walletAddress: 'tz2DurpCmTtZp7YPHmP2hPyonZ3G6VMxqWSQ', name: 'Nujonakihs',
                    metadata: {description: 'Life is Art!? Will the values taught by a tribe from the future, where anything goes, make us happier in our everyday lives? Or not?'},
                }, title: 'O.D #721',
                src: 'https://dweb.link/ipfs/QmR8azpX7EPQqtw9YL8cFd9AFZEbggrm93tgaYxSCGnK1t',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmadMcsEV45Yn3Qty1a9FBp6QutyS98yzssSAWbCbFBNWG', tags: [],
            },
            {
                id: 177341, creator: {
                    walletAddress: 'tz1djJnb5WZx2ypYtqp2UZCVue6TrAd7M2MV', name: 'mentitaDAO',
                    metadata: {description: '❋ collective space in cryptoart of latinamerican artists ❋ promoting arts and circulation of knowledge ･:･゜ﾟ･*☆'},
                }, title: 'Electroplankton',
                src: 'https://ipfs.io/ipfs/QmPZbbGX6L5EF6ePjRX3XpnSvR7NWAcThqn3GJBpBdPLE',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmUrVqPkGcya2vju2wQ7worPnV9yxBaw88gwU5X3yCMcen', tags: [],
            },
            {
                id: 177343, creator: {
                    walletAddress: 'tz1fv8SRiTy7zJRbPJk4ZCc8CtUPzS6LVZPn', name: '',
                    metadata: {},
                }, title: '03 - YELMA (Perfume)',
                src: 'https://dweb.link/ipfs/QmPTDZ9Mi3vhAufTiVwKfVafdZWSvae2c4P8PWynx3xiBA',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmboMVS38mnkC4snkUZbTfdvUuWk2fXrqMrErcqRBpY3Wr', tags: [],
            },
            {
                id: 180023, creator: {
                    walletAddress: 'tz1R7Canwm9D8uvSQfgeibKuAqEekfzYwvai',
                    name: 'GinoFinOcchio', metadata: {
                        identicon: 'ipfs://QmTNgUHk9DR6QpFTycdaKjTDyBmtpAyX54WSRAt17oActL',
                        description: '',
                    },
                }, title: 'ICE787',
                src: 'https://ipfs.io/ipfs/QmdKkZp3zpmB1HojsvLx2sEazxEUsgt7REKmdgENv4mnjZ',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmSXm2XpqfJG4fhv9LeuPZZqhCd2inaAR4CqrSMBhyAc1i', tags: [],
            },
            {
                id: 184521, creator: {
                    walletAddress: 'tz1RWCDAjTJXfQUy99tuL6n1cdj9gnyRzXCt', name: 'yuleaureh',
                    metadata: {
                        identicon: 'ipfs://QmeNLm38exWTFPdZgBkgn87dqEpt37XnwECWsqd1arJJfK',
                        description: 'Visual artist and Musician from Brazil. | Coletivo Arruaça | Sampleada Label www.sampleada.com',
                    },
                }, title: 'Fragmentos vol.1',
                src: 'https://gateway.pinata.cloud/ipfs/QmRUDkAgaEWH2aSeySdwaJT54gYsgFTdCpHXZj8uKTiXxu',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmU1pF6jpGDy6AumhtFD4DPnaQRPyutkK7HTGo4ebnaHc6', tags: [],
            },
            {
                id: 184534, creator: {
                    walletAddress: 'tz1YNGWkQTyNvEvuukFhLehZv7niyAdmuWEp', name: '',
                    metadata: {},
                }, title: 'Catinga',
                src: 'https://gateway.pinata.cloud/ipfs/QmV8QUfPREXUaqr5cT3XiZY9y4NGaDg9uKWxvLDHVnXjyJ',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmZviymv41K61fG3qzqGzvGnZA7Aw7FL7Z2Hx7Df6cVhVN', tags: [],
            },
            {
                id: 185156, creator: {
                    walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S', name: 'Bface',
                    metadata: {description: 'Beats, Design & life'},
                }, title: 'Test Press #2: Flippn Rock',
                src: 'https://dweb.link/ipfs/QmXGNGVHtTFgGZHuAqAk5gvzcPiWHrU6ju2WShrLEXMGDc',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmQy5btPKY9fCmjfhGatbADpFxWaVqct3EAvTZAtH5oKJt', tags: [],
            },
            {
                id: 187125, creator: {
                    walletAddress: 'tz1LsnZE1fbmc5R42QqV7VDqFt9NV8MZ7tmk',
                    name: 'fractalvector',
                    metadata: {description: 'Pedro Kozovits - Musician / Code Artist / Math enthusiast'},
                }, title: 'Analog Journey - Rage Against Humanity',
                src: 'https://cloudflare-ipfs.com/ipfs/QmasbbhzTcvSyKCyE4LXpgNx6rMmsaTL7TMcq9VezQb8f6',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmStLusSuCtm1JQBWYXTAHJbqSPaU5PYfJxaqBC31y6sRo', tags: [],
            }],

    },
    {
        name: 'Hicathon Dev',
        curator: 'HEN Radio',
        description: 'The tracks that made hen.radio, listened to on repeat for hackday development',
        img: '/images/playlist_cover_0.png',
        slug: 'hicathon-dev',
        tracks: [
            {
                id: 48594,
                title: 'A l\'Ouest',
                src: 'https://ipfs.io/ipfs/QmawLCNM666CsHajN7MfJH9baWq2JRshxXX7QETL9dR4NA',
                mimeType: 'audio/ogg',
                creator: {walletAddress: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f'},
                tags: [],
            },
            {
                id: 44540,
                title: 'BUDS',
                src: 'https://ipfs.io/ipfs/QmaRtMtfQEbUEj39gwCSNzcLPhBaTEnTXsFjWjeXNPMe3c',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp'},
                tags: [],
            },
            {
                id: 16396,
                title: 'The Air That Never Was',
                src: 'https://ipfs.io/ipfs/QmXpvmA6R4nJmeZsDXJY2EyUeYcM5iCg2Ww1jtjTnrf5iQ',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1YJvMiZyXnzvV9pxtAiuCFvaG7XoBZhbUQ'},
                tags: [],
            },
            {
                id: 5302,
                title: 'Dub Stars',
                src: 'https://ipfs.io/ipfs/Qmd8vTe22AdcYV84hTD2UEZFDicZZNf4j9bUBfDQsidy11',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f'},
                tags: [],
            },
            {
                id: 41309,
                title: 'Improvisation for Melody Owen',
                src: 'https://ipfs.io/ipfs/QmXLBb1b5c3hA3Rsccs19Zw9PCQEuJiU3drAyfFnTa2ZSP',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1YJvMiZyXnzvV9pxtAiuCFvaG7XoBZhbUQ'},
                tags: [],
            },
            {
                id: 5298,
                title: 'Melancome',
                src: 'https://ipfs.io/ipfs/QmNNrraeevcUhDT4saUA6W1AqiukZvvyRtroCf57PhjjyV',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f'},
                tags: [],
            },
            {
                id: 44528,
                title: '|WOAH}C00L|',
                src: 'https://ipfs.io/ipfs/QmYRADeeCDWyayLm8jrePE7EzVo9NXTBgXSfpshQcMuCEm',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp'},
                tags: [],
            },
        ],
    },
    {
        name: 'Eclectic Coups de Coeur #1',
        curator: 'Lauzaki',
        description: 'A mixed bag of HEN gems',
        img: '/images/playlist_cover_1.jpg',
        slug: 'eclectic-coups-de-coeur-1',
        tracks: [
            {
                id: 17575,
                title: 'Dancing Bones',
                src: 'https://ipfs.io/ipfs/QmNot4YVcRqByEiiNHKwocR1Ncnab9VGdHtUbLKD5Q14bT',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1VQwSyQPA1owaqZ2RUkDEKsdZsfQPVvVbN'},
                tags: [],
            },
            {
                id: 11305,
                title: 'rumpy wants a baby',
                src: 'https://ipfs.io/ipfs/QmUfPW1eBdD7naLGopdpJyXYTezpU46Bkam9d2kx96JoFg',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ZQ3RF4Qk2P9qau3ya4hKMxqq42SEjhbYw'},
                tags: [],
            },
            {
                id: 97695,
                title: 'PEACE',
                src: 'https://ipfs.io/ipfs/QmVX35MDiPpsXW3gtKumNL2j44ZzWr5QPZP5vbgHDE5VoE',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1Uj8B2iVVcVV7FHmFL7PTZdNK4onhXP1Bs'},
                tags: [],
            },
            {
                id: 97684,
                title: 'SUNDAYSUSET',
                src: 'https://ipfs.io/ipfs/QmdmgwMFxarbpEk1eZzUm2JEiBg9VGoLmBphyUDrSbwU4w',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1Uj8B2iVVcVV7FHmFL7PTZdNK4onhXP1Bs'},
                tags: [],
            },
            {
                id: 101079,
                title: 'Crypto Noise series #04',
                src: 'https://ipfs.io/ipfs/QmatzMuSP2XAWDMpjUxmXeFDCSJAtePjhte7J58DE4ssKp',
                mimeType: 'audio/wav',
                creator: {walletAddress: 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC'},
                tags: [],
            },
            {
                id: 9482,
                title: 'gpp udah makan by bagvs',
                src: 'https://ipfs.io/ipfs/QmaJLxXppTPvLJjLFCpntAPT5TwaShxeGEqnFTP6AborBt',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1PTddXFRZDHnzy8k34XiKwy7p2vabY8Qxo'},
                tags: [],
            },
            {
                id: 12095,
                title: 'Malachi Basden and Wes Anderson -- I Can\'t Get Started',
                src: 'https://ipfs.io/ipfs/Qmdq5oLpi5gWPk4QsJ3HcJuAusNr2bV7L1EBHddJYDByUd',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1Z7PUrxjaev1EM2SeGtetiZgZedrYvgFmY'},
                tags: [],
            },
            {
                id: 43386,
                title: 'continuum_after_latency',
                src: 'https://ipfs.io/ipfs/Qmb92ifujVsctJL5R8X25prWjNjjuDCWScysEXiAZSrD2v',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz2MR9zog3QaSKRMsxMRqYtDevwoRKVvMQX7'},
                tags: [],
            },
        ],
    },
    {
        name: 'Ambient Atmosphere',
        curator: 'HEN Radio',
        description: 'Ambient Future Atmosphere',
        img: '/images/playlist_cover_2.png',
        slug: 'ambient-atmosphere',
        tracks: [
            {
                id: 8577,
                title: 'Geometrical Psychology #8',
                src: 'https://ipfs.io/ipfs/QmfHLRCnhFY5oBsmE9gKH6xjFUpbjNcqRG8XKTm52jaiHa',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1TA2GsoJmC6G57DZfMw9cj5Z8ztviGBzU7'},
                tags: [],
            },
            {
                id: 6337,
                title: 'Eurorack ambient jam #1',
                src: 'https://ipfs.io/ipfs/QmUmhLsTPKRjwJN3eNfYAJ9Hw1SaRbC8gQTky9MBPfWcr1',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1etmVTu5kPrSZjQPNF2nE79xyKddjwguyz'},
                tags: [],
            },
            {
                id: 10045,
                title: 'Eurorack ambient jam #4',
                src: 'https://ipfs.io/ipfs/QmVdoqKAQNQNJ8YBGTk6pXsrXNZqvErHNzxKFg7cnPn9xj',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1etmVTu5kPrSZjQPNF2nE79xyKddjwguyz'},
                tags: [],
            },
        ],
    },
    {
        name: 'Experimental Brazil',
        curator: 'HEN Radio',
        description: 'Experimental Brazil',
        img: '/images/playlist_cover_3.png',
        slug: 'experimental-brazil',
        tracks: [
            {
                id: 44945,
                title: 'Bface - Touch Ya!',
                src: 'https://ipfs.io/ipfs/Qmf9BCvmWyTwXjFiyTTswRehfSmBF2JPowYutDH1um4akG',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S'},
                tags: [],
            },
            {
                id: 45003,
                title: 'Bface - 70skrl',
                src: 'https://ipfs.io/ipfs/QmaWPAQjpotsgbv66aECT2SbbSXKDhjF9FxGrozVP2DYyn',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S'},
                tags: [],
            },
            {
                id: 44984,
                title: 'Bface - Vida Severina',
                src: 'https://ipfs.io/ipfs/QmQJ86BBKZKmoM8bJDSZ2AohKeWv1atP21CrudQhukfU8D',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S'},
                tags: [],
            },
        ],
    },
    {
        name: 'House',
        curator: 'HEN Radio',
        description: 'House on the soft side',
        img: '/images/playlist_cover_4.png',
        slug: 'house',
        tracks: [
            {
                id: 56836,
                title: 'Walking Home',
                src: 'https://ipfs.io/ipfs/QmatrNGiVEo5RjNkV27CS2WgwhQkN7i4xN7azLrUewycXB',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
            {
                id: 52492,
                title: 'Stronger (Yeti Tears Remix)',
                src: 'https://ipfs.io/ipfs/QmWHAQEhYuWka4hXx5MQx773tW8ZY76rdJ2io6VfrFECnV',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'ttz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
            {
                id: 40382,
                title: 'The Portal',
                src: 'https://ipfs.io/ipfs/QmWRJpiSnDcu76NvUq9CkY1U2cVaP8Z75G3nArnqbQ1eGa',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
            {
                id: 35832,
                title: 'Aerophobia',
                src: 'https://ipfs.io/ipfs/QmekqLeahzokRF8S6PoRUj6mvXn3xJWErr6oMePkq8pQUX',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
        ],
    },
    {
        name: 'Cryptobeat',
        curator: 'HEN Radio',
        description: 'Cryptobeat glitch',
        img: '/images/playlist_cover_7.png',
        slug: 'cryptobeat',
        tracks: [
            {
                id: 58421,
                title: 'CIRCLE COMPLETE (production GLASSY)',
                src: 'https://ipfs.io/ipfs/QmUVqJPzx9v6WDeWVxxVSe1PrMyibyWtFnioAR7sY42tyG',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'ttz1ZtxSzCJkDNztv2QRP8xgVLafxv9D5aYea'},
                tags: [],
            },
            {
                id: 39331,
                title: 'CANNABIS SAINTS BEAT TAPE [Song 1 Glory and Time]',
                src: 'https://ipfs.io/ipfs/QmVRU7oG6RnJ6dQ1QAUm1Doji2Nfu2cuuCVmBjYNtrHahq',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ZtxSzCJkDNztv2QRP8xgVLafxv9D5aYea'},
                tags: [],
            },
        ],
    },
    {
        name: 'Trance',
        curator: 'HEN Radio',
        description: 'Psychedelic Trance',
        img: '/images/playlist_cover_5.png',
        slug: 'trance',
        tracks: [
            {
                id: 34506,
                title: 'Poliwog - UNR Work In Progress',
                src: 'https://ipfs.io/ipfs/Qmc7rFFKmUzasjej9y3tkjc1kwrWQPjPWdK2gNdFFymdbu',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1MUcbDL1UbE4DTibDuDs8dLnih4u6Ka8uT'},
                tags: [],
            },
            {
                id: 77720,
                title: 'Unreleased Psychedelic Trance Track 2 by Poliwog',
                src: 'https://ipfs.io/ipfs/QmQpPXELuT88xHpKo7FF4F68pv2vDe7txkXMDYo6fH3nQ7',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1MUcbDL1UbE4DTibDuDs8dLnih4u6Ka8uT'},
                tags: [],
            },
        ],
    },
];
