export const playlists = [
    {
        name: 'Hen.Radio Halloween',
        curator: '@hen_radio',
        description: 'Halloween 2021 Hen.radio playlist',
        img: '/images/Halloween2021_Playlist_Cover_256.gif',
        slug: 'hen_radio_halloween2021',
        tracks: [
        {"id":157397,"creator":{"walletAddress":"tz2GP2o3kMJ8Q22FdjBo6QeheqUTAyEkHBo4","name":"marcfendel","metadata":{"description":""}},"title":"Ol' Spooky","src":"https://cloudflare-ipfs.com/ipfs/QmTA4U39xuWb4cRMTpuAnbVHGNJ3K53biBKo6ajVhA2Mp8","mimeType":"audio/mpeg","displayUri":"ipfs://QmSmbteyHrZx9aW9RXg3BiTzaNP5u9BtvkyTqLVJnwF1Nh","tags":[]},
        {"id":444585,"creator":{"walletAddress":"tz1gSFXCzGW8Jo3raLgx7vv33stSYnh67tyu","name":"sikerial","metadata":{"identicon":"ipfs://Qma98rFB2PscJcTwM1hp9majGsfm8eA9SP1KcVjHc3Tq4K","description":"artist | musician"}},"title":"Hypno skull","src":"https://cloudflare-ipfs.com/ipfs/QmfRi237TP5UfG9xizsruQfcqmSaSo5WKp3LzYpzapUUr5","mimeType":"audio/mpeg","displayUri":"ipfs://QmbboHkuSZnXhmf3qu6VeHNhZ9Q8dou4QgiaNdN8yg4vzy","tags":[]},
        {"id":438073,"creator":{"walletAddress":"tz1RB4BveChbSXQp9FjTJqM5UprD7EwXYsDi","name":"LilAstro","metadata":{"identicon":"ipfs://QmX3LMnAAjb75gzjZ1oFFRqHBS4Zw327kvsy8kXixc27mE","description":"NFT Artist/Rapper/Producer/Videographer Feast your eyes on these Trippy and Unique artworks! 0.0"}},"title":"Lil Astro - Cactus Creeper","src":"https://infura-ipfs.io/ipfs/QmWgkmw5kWbGra9RSJh3Rj5U1KejFfTwQW7tTSQeMLYrz2","mimeType":"audio/mpeg","displayUri":"ipfs://QmXr6LYxMdxhBGxPzBki8aqxZxyBb5oWuLJDkhNrAmyrV7","tags":[]},
        {"id":479009,"creator":{"walletAddress":"tz2GP2o3kMJ8Q22FdjBo6QeheqUTAyEkHBo4","name":"marcfendel","metadata":{"description":""}},"title":"Alps Nightclub","src":"https://dweb.link/ipfs/QmRkUvibpeEcXHdrhkgmnf4U4Zm39Hth8aBDEHYW3cSUjH","mimeType":"audio/wav","displayUri":"ipfs://QmRQLinSNbfSwoczSmSvBhgAGU1io25yyKNNecduJBFQRN","tags":[]},
        {"id":393288,"creator":{"walletAddress":"tz1gSFXCzGW8Jo3raLgx7vv33stSYnh67tyu","name":"sikerial","metadata":{"identicon":"ipfs://Qma98rFB2PscJcTwM1hp9majGsfm8eA9SP1KcVjHc3Tq4K","description":"artist | musician"}},"title":"Halloween Vibes","src":"https://infura-ipfs.io/ipfs/QmbWrHKwNjeZZsjSkgXFy52UgsvXU3FN2oY3UTjuiw2hyC","mimeType":"audio/mpeg","displayUri":"ipfs://QmSjFyCBj6rAct4dvkPFh1U6NUijToVjYB2izoqY9wxqKY","tags":[]},
        {"id":382442,"creator":{"walletAddress":"tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR","name":"zimbabwe3000","metadata":{"identicon":"ipfs://QmeXLDQDEE4XKFGX7ggUvhGsnhZ1CmRo9Yi1R3JohFv1kc","description":"dark jazz/trip jazz legend"}},"title":"It's Like You Heard It Many Times Before","src":"https://ipfs.io/ipfs/Qmda82nRUjQq24FfGUJvrPycQU6tyugKLMzKmyrnHL4vGD","mimeType":"audio/wav","displayUri":"ipfs://QmPA2xJkR2C1mRDbwqMUWzGcq1GYnRLrosZidGMkZ2tko1","tags":[]},
        {"id":382400,"creator":{"walletAddress":"tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR","name":"zimbabwe3000","metadata":{"identicon":"ipfs://QmeXLDQDEE4XKFGX7ggUvhGsnhZ1CmRo9Yi1R3JohFv1kc","description":"dark jazz/trip jazz legend"}},"title":"When The Winds Are Black","src":"https://cloudflare-ipfs.com/ipfs/QmZX7XiNfhoSZsn6mMBiwzF9zzt4r8bcd8ENKsXrvZaj62","mimeType":"audio/wav","displayUri":"ipfs://QmVxSXf9To4aNvT7355D3ngXpazEHMMFbug6NuDjutdSoA","tags":[]},
        {"id":293999,"creator":{"walletAddress":"tz1fBRQrpjuLtqrpPK6Us3W2nJfd6CFdJerJ","name":"INspireENcrypt","metadata":{"identicon":"","description":""}},"title":"Dont Stop Keep Going","src":"https://ipfs.io/ipfs/bafybeiarv5jwbwmqo3f6ta2ocz62nsa6wj7dvqiqxaeb6wuovqmdngxiue","mimeType":"audio/mpeg","displayUri":"ipfs://bafkreiavpgf5cwkcvccjfqg2o6rtlszht3k3rjdu2eq23e3jj72rttv3ua","tags":[]},
        {"id":285137,"creator":{"walletAddress":"tz2G2NzfXg5JDLcCQxGmToT8goBBGPwo1dtj","name":"analoguei_o","metadata":{"identicon":"ipfs://QmdxBw1SEYigmJu8SV7EA8zawXKeYgyB9xJKnRVgU71guX","description":"The conversion of reality to binary noise. Dogs. CHaos. These are the scriptures by which I live. Art, in all its forms."}},"title":"2. Helix Sky","src":"https://ipfs.io/ipfs/bafybeidha57hdnfcjvlhvicuehmbsfz4jgfixdyddvzzhguetgr7r2d4zy","mimeType":"audio/mpeg","displayUri":"ipfs://bafkreiafuuqttpmaapnvnxjyu4vuqrlfwf7gyry2j6jpa37jues2p5e32e","tags":[]},
        {"id":204490,"creator":{"walletAddress":"tz1fBRQrpjuLtqrpPK6Us3W2nJfd6CFdJerJ","name":"INspireENcrypt","metadata":{"identicon":"","description":""}},"title":"Mindstate Management","src":"https://cloudflare-ipfs.com/ipfs/QmQAFx2rmu9EjYCRWpGpbNt38Jypojn4wgWCujbBxNyfth","mimeType":"audio/mpeg","displayUri":"ipfs://Qmdx7HwHpBGYuESud2eQNYDgpi7ufuM9aKPgyU6zqkxrUg","tags":[]},
        {"id":174969,"creator":{"walletAddress":"tz2DurpCmTtZp7YPHmP2hPyonZ3G6VMxqWSQ","name":"Nujonakihs","metadata":{"description":"Life is Art!? Will the values taught by a tribe from the future, where anything goes, make us happier in our everyday lives? Or not?"}},"title":"O.D #719","src":"https://ipfs.io/ipfs/QmcLEQHLFS6pdvEJi8y54mbfpG1bC9BPACwJPPvUZbDTNo","mimeType":"audio/mpeg","displayUri":"ipfs://QmdT4DXY5JL5RRnYAD4J8uqYMdRXb1ygrkx2C3dPNnMoUy","tags":[]},
        {"id":35832,"creator":{"walletAddress":"tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX","name":"","metadata":{}},"title":"Aerophobia","src":"https://cloudflare-ipfs.com/ipfs/QmekqLeahzokRF8S6PoRUj6mvXn3xJWErr6oMePkq8pQUX","mimeType":"audio/mpeg","displayUri":"ipfs://QmWWVpQUNAF3kyLBUcL7HUJUkpL9gxanNpwNUb1r6rdi2L","tags":[]},
        {"id":458816,"creator":{"walletAddress":"tz1VPUDAJk5Aj3ssKszAnfXDYtAkAyrWik5L","name":"savr_dave","metadata":{"identicon":"ipfs://QmepHK88piquD5Dce21FgBYnete1nKm6PQsn1m6e7sHmk2","description":"savrmusic.com"}},"title":"Transient 010","src":"https://infura-ipfs.io/ipfs/QmRMgdXJDSwAfgWnGnKJVWxytfQRwmXvskX8WGtctxJYGE","mimeType":"audio/wav","displayUri":"ipfs://QmY73o7vudC14wPo33BEowe5jtr2jA3T21TGsfTkyhzghi","tags":[]},    
        {"id":472141,"creator":{"walletAddress":"tz1VPUDAJk5Aj3ssKszAnfXDYtAkAyrWik5L","name":"savr_dave","metadata":{"identicon":"ipfs://QmepHK88piquD5Dce21FgBYnete1nKm6PQsn1m6e7sHmk2","description":"savrmusic.com"}},"title":"Transient 011","src":"https://gateway.pinata.cloud/ipfs/QmWW8RqDWN3Fwz1KrXizAKFaT2DBL63TmgWfEqR3mk4YSo","mimeType":"audio/wav","displayUri":"ipfs://QmVL9TsibzsWthHuJr6fEgQHf5AAAwKTB4Z47JkKzkAiFU","tags":[]},
        {"id":471026,"creator":{"walletAddress":"tz2DurpCmTtZp7YPHmP2hPyonZ3G6VMxqWSQ","name":"Nujonakihs","metadata":{"description":"Life is Art!? Will the values taught by a tribe from the future, where anything goes, make us happier in our everyday lives? Or not?"}},"title":"in c","src":"https://cloudflare-ipfs.com/ipfs/QmNptWTX6EkYUDkSb5ovoX2bJ4YHwYXBYT4PrDecwM6D9r","mimeType":"audio/mpeg","displayUri":"ipfs://QmQKeGLDG37FcEfMrMQdxkzgfJkgaGd29qdZb9VCmruKwk","tags":[]},
        {"id":422572,"creator":{"walletAddress":"tz1VPUDAJk5Aj3ssKszAnfXDYtAkAyrWik5L","name":"savr_dave","metadata":{"identicon":"ipfs://QmepHK88piquD5Dce21FgBYnete1nKm6PQsn1m6e7sHmk2","description":"savrmusic.com"}},"title":"Transient 003","src":"https://gateway.pinata.cloud/ipfs/QmPvVmzEnstTBDJS2fVTuGdwRmV9vr1mnMwqhf1iaVesni","mimeType":"audio/wav","displayUri":"ipfs://QmZtNjn5CFhsJpJC74fK915mhEN2F4qQEaGAvGuYuWcrwB","tags":[]},
        {"id":401528,"creator":{"walletAddress":"tz1VPUDAJk5Aj3ssKszAnfXDYtAkAyrWik5L","name":"savr_dave","metadata":{"identicon":"ipfs://QmepHK88piquD5Dce21FgBYnete1nKm6PQsn1m6e7sHmk2","description":"savrmusic.com"}},"title":"Transient 001","src":"https://cloudflare-ipfs.com/ipfs/QmPhGqunmu8e6AdAu6K1kMRQhti6oYE9KmUJoShDhcTLxr","mimeType":"audio/wav","displayUri":"ipfs://Qmch8iEXKw7XjAa5uA4xvGm3CRndTsQ7znZVcFdnBv4xa3","tags":[]},
        {"id":470057,"creator":{"walletAddress":"tz1VvS1nZoTock4aj52n38ghA8JLzAx8yFmi","name":"sphere_of_mars","metadata":{"identicon":"ipfs://QmR7iHHyDW8xD2AJPo9nnL4hTm2jTrDNW2sbABgQUYjP4V","description":"electronic experimental space music"}},"title":"Voices - 05 It's Here","src":"https://ipfs.io/ipfs/QmdrT88PFgdYUwVsk7od7RYfwxMXJf6GRBTiXKMGJzC9h9","mimeType":"audio/mpeg","displayUri":"ipfs://QmcT35QVdwRmQdgQ3U8zr1hsbVyTxb94KXytUAh3GYbx5W","tags":[]},
    ]
    },
        {
        name: 'Hen.Radio jingle #1',
        curator: '@hen_radio',
        description: 'A playlist of music artists having contributed to Hen.Radio jingle #1',
        img: '/images/V5MT_HEN_Radio_180X180.gif',
        slug: 'hen_radio',
        tracks: [
            {
                'id': 195132, 'creator': {
                    'walletAddress': 'tz1QbNsyBSznN3T4eQsHtFjhNbjwsu3iEZ5G',
                    'name': 'EJKEW',
                    'metadata': {'description': 'ttps://soundcloud.com/ejkew-1/sets/myrcene track from the B-MYRCENE PROJECT, comes with FROOTS print.'},
                }, 'title': 'TROPICAL PUNCH',
                'src': 'https://ipfs.io/ipfs/QmQe8Y3eRT93zrxiRCAJoqAmj8wNxfhDvvCSLuUBACbAtN',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmStVvBz9qWedMoYhPhyzUHMX1Kzwgkt7xnVwhq1SpfXgK', 'tags': [],
            },
            {
                'id': 180278, 'creator': {
                    'walletAddress': 'tz2DurpCmTtZp7YPHmP2hPyonZ3G6VMxqWSQ',
                    'name': 'Nujonakihs',
                    'metadata': {'description': 'Nujonakihs is a Zipangri creator. I make things that belong to the sphere of culture or entertainment.'},
                }, 'title': 'O.D #721',
                'src': 'https://ipfs.io/ipfs/QmR8azpX7EPQqtw9YL8cFd9AFZEbggrm93tgaYxSCGnK1t',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmW8HgCvZGDjv7WPEXNYhSzTW9MQVwsTRZ6mNCgJCk9QKd', 'tags': [],
            },
            {
                'id': 217384, 'creator': {
                    'walletAddress': 'tz1Mpr7WD3UG47UFPbizLPnBCNhh8pcdbSyz',
                    'name': 'V4W.ENKO',
                    'metadata': {'description': 'v4w.enko - "RE-03_snd". The first 11 seconds of original soundtrack for the objekt porting to  non fungible token of the audiovisual artwork "RE_w-03 [Resolution of the Energy _white]". This is procedural sound I made with my custom instrument - node based synthesizer I created by myself with custom coding in the software of Max/Msp. It is a combination of generative "golden ratio" based sequencer, additive synthesis and some tricks with realtime rhythmic/harmonic structure.  All components are recorded in realtime from the live algorithm.  Mixed into one. listen / use / mix.  No sound effects are used. Pure wave physics.  Microsound. '},
                }, 'title': 'v4w.enko - "RE-03_snd"',
                'src': 'https://ipfs.io/ipfs/QmZT99Yyep5NQGbqQZRjvNG7wTiN6UpqgKW3fQ7RHBWEMF',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmadMcsEV45Yn3Qty1a9FBp6QutyS98yzssSAWbCbFBNWG', 'tags': [],
            },
            
 ],
    },{
    name: 'The PeaceMakers  - The Lockdown Sessions',
    curator: '@makingdpeace',
    description: 'Two old friends, separated by time (decades) and space (each side of the world), unlocked some music whilst locked down.',
    img: '/images/peacemakers2.jpg',
    slug: 'makingdpeace',
    tracks:[
        {"id":365225,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - The Drones","src":"https://dweb.link/ipfs/QmdNttDvYuNBKc5hxo9LP384v7c5YSVwWMsLtyRreXVtrx","mimeType":"audio/mpeg","displayUri":"ipfs://QmepzWr4KbT7FPmMEG7tcw7egXertKUncSeL2t9UpaD8Zg","tags":[]},
        {"id":365199,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - The End is in Twittershite","src":"https://dweb.link/ipfs/QmQigQ5VEhXZsm4F1vjTQ6zyTRt2WFbfobY9oEWZbzCQX5","mimeType":"audio/mpeg","displayUri":"ipfs://QmeFeQuHA8ZDVm4YTgrp1nGmVMoVXYM2Sk5p2VdmembXvK","tags":[]},
        {"id":365038,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - 25Hr Party People","src":"https://dweb.link/ipfs/QmcUEcshRmyJa3z26B9dXXSJqQjHN7jsbisbZDJ3pYvgnB","mimeType":"audio/mpeg","displayUri":"ipfs://QmcgGYQQGwLBztCdjUVrB96fWSQuBAaR8ojtayVohM566d","tags":[]},
        {"id":365015,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Drive Away","src":"https://infura-ipfs.io/ipfs/QmeKRDKwzoNgP1rJDD7XUWE5j7cQfDvtx6VmPCsE1ySMsR","mimeType":"audio/mpeg","displayUri":"ipfs://QmbDJyomsFSbxG6ECCBAAezCpNFsUXJ89VRSiLHMNTwnLt","tags":[]},
        {"id":364997,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Ballad of the Algorithm","src":"https://gateway.pinata.cloud/ipfs/QmXRhjPBM5dZH6rg4upDnX6U9Y7uKB7KtJuLgLwUcV1tRZ","mimeType":"audio/mpeg","displayUri":"ipfs://QmVXfZi2aTuVsqtV29gjCT8Xr9othuRDevswArxbhoMq6B","tags":[]},
        {"id":364954,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Kitchen Love","src":"https://dweb.link/ipfs/QmNz11XYVUZpVdj5RRfgP8DcdyPVyTuNgjFuoWnvfzQfNY","mimeType":"audio/mpeg","displayUri":"ipfs://QmfBNfqnbZEPfxrs7KtphaANBsq7UXPAgk9krTNM4vmiw3","tags":[]},
        {"id":364927,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Swede Pecking","src":"https://dweb.link/ipfs/QmQNWntCGSoaNPquupLH2krEKsaAjTdjFrujMq4K3TcDBR","mimeType":"audio/mpeg","displayUri":"ipfs://QmSQHxAEaaVvreubUZtXkCKFoDV22WSLTHX66A6VLPG24T","tags":[]},
        {"id":364902,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Empty Promises","src":"https://infura-ipfs.io/ipfs/QmRjj4RWkp2VQtwja6kXxycuiL5wDUDvRaNMLsjmBsg9vk","mimeType":"audio/mpeg","displayUri":"ipfs://Qma7GbE2VoWuC4a67ncpL9u9bSRjXrP5gmsLEzoZNnP64K","tags":[]},
        {"id":364886,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Dont Know","src":"https://infura-ipfs.io/ipfs/QmPxE4z1d3G71Fhyk9a1NQwxpzwHQPQ3a4UTr2TbZQ6GWe","mimeType":"audio/mpeg","displayUri":"ipfs://QmRszvetXwd8mhijHPN7dKXchGvgACafp4WbLq3kgaopVv","tags":[]},
        {"id":364870,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - The Olympic Flame","src":"https://gateway.pinata.cloud/ipfs/QmbybBvkoZY9EHGjsUzeAC1b3q1BxyiHRUWvrvwKqfd98d","mimeType":"audio/mpeg","displayUri":"ipfs://QmWaW6yYjhvTVUnbDVZXpyrqo8awzHNLCNXN34YDATgwBB","tags":[]},
        {"id":364841,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Satisfied","src":"https://gateway.pinata.cloud/ipfs/QmPYbq8UjSVgkv7DFErZNiCY7yUbdE5zkNni17sDeYLyij","mimeType":"audio/mpeg","displayUri":"ipfs://QmfBFtqsBcnPP9FoZudSL9kyoTVoTH7Vz8YYZAGdfqEKTp","tags":[]},
        {"id":364822,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - A Thinka on a Finca","src":"https://infura-ipfs.io/ipfs/QmX9MtjKXhHYSzDncv8R9EnHVan6aKDHPDRb9D9vzoRBPW","mimeType":"audio/mpeg","displayUri":"ipfs://QmbvuS88mqcXmUaKNWTHdHjpau9tE3b6NvAUxra4riEhk3","tags":[]},
        {"id":364792,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers","src":"https://cloudflare-ipfs.com/ipfs/QmbZWNCJBcns261x3xbFSoRJ8L59aPGGMVgfpQs3XYn2pu","mimeType":"audio/mpeg","displayUri":"ipfs://QmbEBkK5XRqYjEskcySfx2LdWxtj2aeHTDoEk4zPrqdGYy","tags":[]},
        {"id":471675,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Towers","src":"https://ipfs.io/ipfs/QmRzRR1JdhPJsnhsNC9xobNfkoJpRTCoyiY8f2KLFmzohq","mimeType":"audio/mpeg","displayUri":"ipfs://QmVQJkruZduSyZMd3i1fAFPETcQXZEEiNwV4W2k5sqgNxk","tags":[]},
        {"id":428438,"creator":{"walletAddress":"tz1Zy3p3yAqBAmJyGv3V9wA4yNW1GjUPzDJ5","name":"peacemakingrecords","metadata":{"identicon":"ipfs://QmbKT1vur5P7A5UfuiGPgY27Qg3HvRyk9UNSReCHUirHV2","description":"A travelling musician wandering the metaverse"}},"title":"The PeaceMakers - Alone","src":"https://ipfs.io/ipfs/QmbnsyM2sVBXewD34HgKcxVdpetPMT4wSJHWhFsSLJc7s4","mimeType":"audio/mpeg","displayUri":"ipfs://QmYNWbmHNu5RggkVeM4HC64bzDdnaLRnPJqaieiWqPU3gf","tags":[]},
    ]
},
    {
        name: 'Echoedreaming - Songs From The Dream',
        curator: '@DmitryGruber',
        description: 'This album was recorded in a week, and it is backed by many years of experience with different music and sounds. In every song guitars have different tunings, scale lengths, setups and even string-calibers. It contains beautiful femme vocals, a lot of shimmer delays/reverbs and many-many other interesting things.',
        img: '/images/_OUOw70f.jpg',
        slug: 'DmitryGruber',
        tracks:[{"id":299978,"creator":{"walletAddress":"tz1PQKRX51E1A7CiZxxZzFNw6cJgc6cj8UyN","name":"echoedreaming","metadata":{"identicon":"ipfs://QmW6aMMz1imrUqUPLndgjcdLYVVRbeFKs3xdRuTVmE5oie","description":"Dream-pop / Shoegaze artist"}},"title":"Broken Coast","src":"https://ipfs.io/ipfs/bafybeiclxyenesrgplswrsdrthyksddux4xbs6ilk3gqun3rcr7qw67wjq","mimeType":"audio/mpeg","displayUri":"ipfs://bafkreib54ibaxg7pksc5dyirasafly5xldypfalb44lkpcpl6dsl3f47aa","tags":[]},{"id":299939,"creator":{"walletAddress":"tz1PQKRX51E1A7CiZxxZzFNw6cJgc6cj8UyN","name":"echoedreaming","metadata":{"identicon":"ipfs://QmW6aMMz1imrUqUPLndgjcdLYVVRbeFKs3xdRuTVmE5oie","description":"Dream-pop / Shoegaze artist"}},"title":"Soulmates","src":"https://infura-ipfs.io/ipfs/bafybeifxpjlsy6kxz4zbynfjccbfqd6eps5qk2r7piydtgsvynjyvqq6ee","mimeType":"audio/mpeg","displayUri":"ipfs://bafkreiamp5yqs3nuthtjk4bbpa74gmlpsahagf7fde7qy6u2mqaweg256m","tags":[]},{"id":299930,"creator":{"walletAddress":"tz1PQKRX51E1A7CiZxxZzFNw6cJgc6cj8UyN","name":"echoedreaming","metadata":{"identicon":"ipfs://QmW6aMMz1imrUqUPLndgjcdLYVVRbeFKs3xdRuTVmE5oie","description":"Dream-pop / Shoegaze artist"}},"title":"Boat Made Of Stars","src":"https://infura-ipfs.io/ipfs/bafybeifqpfqugayx5oygojpq46j33o3www47sxgcvmxc5en3ud7bwzcaoa","mimeType":"audio/mpeg","displayUri":"ipfs://bafybeigjvrghjlw7ealupdmoqz4y7vbv4qgm6rqs34t73irkez46tyryiy","tags":[]},{"id":299915,"creator":{"walletAddress":"tz1PQKRX51E1A7CiZxxZzFNw6cJgc6cj8UyN","name":"echoedreaming","metadata":{"identicon":"ipfs://QmW6aMMz1imrUqUPLndgjcdLYVVRbeFKs3xdRuTVmE5oie","description":"Dream-pop / Shoegaze artist"}},"title":"Catch The Wave","src":"https://dweb.link/ipfs/bafybeiaakenyfc4pbpq2xymzfrddnmjxrelljaz2l7fjbzkatfal4xze3q","mimeType":"audio/mpeg","displayUri":"ipfs://bafkreice3xoahxflshg7zoi5o7yt7mclxyq2qxwn3l7ett5ragknvvv7jm","tags":[]},{"id":299909,"creator":{"walletAddress":"tz1PQKRX51E1A7CiZxxZzFNw6cJgc6cj8UyN","name":"echoedreaming","metadata":{"identicon":"ipfs://QmW6aMMz1imrUqUPLndgjcdLYVVRbeFKs3xdRuTVmE5oie","description":"Dream-pop / Shoegaze artist"}},"title":"Hypnotic Dream","src":"https://infura-ipfs.io/ipfs/bafybeif7ge2qa73d3hqrzpywh3evtuefkas2jmx6arjqcqzqqvutsevcqq","mimeType":"audio/mpeg","displayUri":"ipfs://bafybeihqk7ojrpwwuf2quitztin3oazrngekf5l55amejbs5pgi5dmfnoe","tags":[]}]
     },
    {
        name: 'GabPol',
        curator: '@GabrielPolitzer',
        description: 'Sound artist, musician and biologist from Rio de Janeiro.',
        img: '/images/GadPol.png',
        slug: 'GadPol',
        tracks: [
{"id":240344,"creator":{"walletAddress":"tz1MM2wfCrRzGvXYTt1BsChqsACaF5SJQiVN","name":"GabPol","metadata":{"identicon":"","description":""}},"title":"A SINGLE FURNITURE // FURNITURE SONGS","src":"https://gateway.pinata.cloud/ipfs/QmYbJVBviQgzNoFpU8vMuPHSPMLTtMt12we4E5rJReCRR5","mimeType":"audio/mpeg","displayUri":"ipfs://QmRWsLCogBrLaccFk9PKzMgExCtX56CugsoRYHNv34PA7y","tags":[]},{"id":241060,"creator":{"walletAddress":"tz1MM2wfCrRzGvXYTt1BsChqsACaF5SJQiVN","name":"GabPol","metadata":{"identicon":"","description":""}},"title":"LIV // FURNITURE SONGS","src":"https://cloudflare-ipfs.com/ipfs/QmYfP4vNpbJ8Zoxqktmiv6FrX3SbCosiR8qMNhGbMBM8of","mimeType":"audio/mpeg","displayUri":"ipfs://QmRdwn7dLVvseyWxS5gBLytegD4TeVBA2HBVWVXTFw5Sii","tags":[]},{"id":243371,"creator":{"walletAddress":"tz1MM2wfCrRzGvXYTt1BsChqsACaF5SJQiVN","name":"GabPol","metadata":{"identicon":"","description":""}},"title":"SELF-ISOLATION // FURNITURE SONGS","src":"https://ipfs.io/ipfs/QmYoRpvUD2pcaKWes2gmywdwZNvbkTimfjQyMg3p2uBU5x","mimeType":"audio/mpeg","displayUri":"ipfs://QmVisQdb3hL8TUWFnHZY7VBedGH6nv1d3EzmqUf1CMsJFu","tags":[]},{"id":247523,"creator":{"walletAddress":"tz1MM2wfCrRzGvXYTt1BsChqsACaF5SJQiVN","name":"GabPol","metadata":{"identicon":"","description":""}},"title":"DANCING SLOWLY // FURNITURE SONGS","src":"https://gateway.pinata.cloud/ipfs/QmSfwC8BfrhFHPP5ZH4LGdmFrhVF4oercsNAsithAEZ6i1","mimeType":"audio/mpeg","displayUri":"ipfs://Qme7xjegvgC1mATJxRgANtqcRk4xqVcPS4UZBah6iMHNMk","tags":[]},{"id":251449,"creator":{"walletAddress":"tz1MM2wfCrRzGvXYTt1BsChqsACaF5SJQiVN","name":"GabPol","metadata":{"identicon":"","description":""}},"title":"CURRENTLY USING A MEDICATION // FURNITURE SONGS","src":"https://ipfs.io/ipfs/QmQfmGNKJH75LatciYir6iMCUYmqZqvqwNFDtbFPBFhpP6","mimeType":"audio/mpeg","displayUri":"ipfs://QmRmkreKxZSMCAJoDeNJ13XjjKVckbph4USmbEcy7cS518","tags":[]},{"id":255866,"creator":{"walletAddress":"tz1MM2wfCrRzGvXYTt1BsChqsACaF5SJQiVN","name":"GabPol","metadata":{"identicon":"","description":""}},"title":"BUENO SONORO // FURNITURE SONGS","src":"https://infura-ipfs.io/ipfs/QmbKKxAiQaDh4NexC4bSs1fLLpoXzruyqm2QJcNTavkimN","mimeType":"audio/mpeg","displayUri":"ipfs://QmVWZkhiJYivhuqynoGEix3Cc48H6FLvpy7mL4NTfEZdb6","tags":[]}
,],
    },
    {
        name: 'Zimbabwe3000',
        curator: '@DmitryGruber',
        description: 'Music compilation of legendary dark jazz artist Zimbabwe3000. These sounds may be described like "music for listening silence" or "late night music',
        img: '/images/Zimbabwe3000.jpg',
        slug: 'Zimbabwe3000',
        tracks: [
            {
                'id': 239994, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': "It s like diving into the sky, a kiss of heaven latenightjazz nightcitymusic doomjazz noirjazz postjazz soundtrack contemporaryjazz music darkcabaret nftmusic tripjazz darkjazz ambientjazz"},
                }, 'title': "When It's Better Than Ever",
                'src': 'https://ipfs.io/ipfs/QmZKQBNPQzVc65hLGQpLXV18HBVYe92zPMuNnn7vs3AcAb',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmQNFBm3G5UR3CGFmsdmchombf2DMRevzEVgTnH8M8GmVD', 'tags': [],
            },
            {
                'id': 240038, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': "I'm not sure about what I'm feeling here but you can feel it"},
                }, 'title': "Where It's Dark",
                'src': 'https://ipfs.io/ipfs/QmZw4jMskdkZiNEtScDh46BDKvfwbd5NLa7LLgVbatg8vD',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://Qmf1s9Jpq7KdrA3HMhW4x5qhF1Kg8k6zXkwhtK247vBaBE', 'tags': [],
            },
            {
                'id': 240048, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': 'Music for listening silence'},
                }, 'title': 'Music To Listening Silence To',
                'src': 'https://ipfs.io/ipfs/QmV6Wmv7eHEuXffjm2zmwRqF7vZQgUyKDnm4pe1hVYgRWu',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmVes4eMqBUo5JYnAm5zV2Zn781GMehHWgmdLxmLBtLMXJ', 'tags': [],
            },
            {
                'id': 240004, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': "Gaze the lights, don't ask"},
                }, 'title': 'Gazing The Lights',
                'src': 'https://ipfs.io/ipfs/QmYUtXJvAUgXDPt2hSUnBc68s8TYnh2GEaa5hykh8359VB',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://Qmco4L6XddnQkUgPtSkGcZS64A5zQJQuBrkAxj6TLrDe7q', 'tags': [],
            },
            {
                'id': 240077, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': 'Dance slow, let the world burn behind your eyes'},
                }, 'title': 'Slow Dance',
                'src': 'https://ipfs.io/ipfs/QmZ3ov5x5BtVVhdHbd4D3VALc2BtEZpaRoF6Kph66LSbiv',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmRNwH6QHHGtTbKP4LuP1WSb74MMVRXWtdGxV4dtCMTmqg', 'tags': [],
            },
            {
                'id': 239989, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': 'Just Follow The Sound'},
                }, 'title': 'In A Relaxed, Lazy Manner',
                'src': 'https://ipfs.io/ipfs/QmRwWLQFtRc7SnUAvzL4EEuTf8TxXwPw4TkRdohpi3vZ26',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmXXcr8VGGjuZQTdNwjWPadpzNB8cZ6YLSmZChRsa5tuBN', 'tags': [],
            },
            {
                'id': 240062, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': 'The sound of time, the sound of life, the sound of nothingness'},
                }, 'title': 'Nocturne №2',
                'src': 'https://ipfs.io/ipfs/Qmefn13wJc3m2k8UXmXcVPGJMSSEfs1WDipXa8urSRVyPT',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmVKfzJ5Ckrk4AFsepWVZyFgzZqt2BLe7h71828kLnCHQQ', 'tags': [],
            },
            {
                'id': 240030, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': "Sometimes it's a dream, other times it's a nightmare. There are two kinds of nightmares: Those that stay and those that leave"},
                }, 'title': "Yes, It's Like A Nightmare Sometimes",
                'src': 'https://ipfs.io/ipfs/QmQc9X9XUG1rfhBifckxf2BhCPRJhhv1uJVmrPGpTpUAy8',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmWfnEiMLzzA2491R4R2kgHP1xWnxkMeE5cLacfwfE9QQB', 'tags': [],
            },
            {
                'id': 239976, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': 'This is a song of hope for the future. If people stop fighting and start bumping more, things will change for the better'},
                }, 'title': 'Cruising The Night, Looking For Bumping (Commercial Song)',
                'src': 'https://ipfs.io/ipfs/QmbKqRE6rJfRhaykwyjYHGc3NkiCUVX6KicU9ekSspR8X4',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmUg4kUttKuZ82uxKb9exZvzHnKnXzcpPamQdbLhc92wqi', 'tags': [],
            },
            {
                'id': 239964, 'creator': {
                    'walletAddress': 'tz1Rmjn3ga5CvXDSnPTV8k5M2QprJkBPRHBR',
                    'name': 'zimbabwe3000',
                    'metadata': {'description': 'The people in the world are living without a sense of time. They live in a “future desert” of uncertainty'},
                }, 'title': 'Song For The Future Deserts',
                'src': 'https://ipfs.io/ipfs/QmSY5rjokfD9LdqxP4X6TF4pVbzfZDygP25pQSUbCCNcuz',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmR69VD2smnVCc8LUzs4zavwzAbAuvyE6H3w8JX7WCZsUu', 'tags': [],
            },],
    },
    {
        name: 'Nomad Label',
        curator: '@hen_radio',
        description: 'Various Nomad_label sound objkts',
        img: '/images/nomad_label.png',
        slug: 'nomad-label',
        tracks: [
            {
                'id': 98380, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #00',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmQCSnBGmQoKNC43kddTqdNWJXM2nEiEf6zXJd88T8Wqex',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmRzzN8NmeiB7KhjhzQiEyG4aUnkrb92JCZZDDYkvhL7DS', 'tags': [],
            },
            {
                'id': 99466, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #01',
                'src': 'https://dweb.link/ipfs/QmNn5PQyDRfLQ9HYQiFhd8ikQTQnRpe3NQ3wMVsjoKo4LW',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmRH9rf5N3nXE6U8iV6z8Fd56g2mqfc9DNMGwrVGV7F2ZN', 'tags': [],
            },
            {
                'id': 100843, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #02',
                'src': 'https://ipfs.io/ipfs/QmdSgdkusmiKea2u4PzESaipZKbttpo48s7tYp5i63j3BD',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmYKkQi4V26o4MHtTSgcdvjePuh8S7hrnpyj4gBcFY4r8i', 'tags': [],
            },
            {
                'id': 100943, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #03',
                'src': 'https://ipfs.io/ipfs/QmRwbLVhnXFKqHz1trzpxWzE6QtNqxWkppM7pb7JNHtzHD',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://Qmctv8KjqBGyqN6gQ7Ap22Y8cTaJ1g1NqZLbC14DG5b3TW', 'tags': [],
            },
            {
                'id': 101079, 'creator': {
                    'walletAddress': 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
                    'name': 'blusimonwasem',
                    'metadata': {'description': 'Nomad Trans-disciplinary Brazilian Artist. CryptoNoise. Daily life simulacrum'},
                }, 'title': 'Crypto Noise series #04',
                'src': 'https://ipfs.io/ipfs/QmatzMuSP2XAWDMpjUxmXeFDCSJAtePjhte7J58DE4ssKp',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmdrM9XZELeuf4dqfCWCqmWonS7znSyGsEA512Dbo143k3', 'tags': [],
            },
            {
                'id': 194594, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'cryptochristo - ode to joy tape speed distortion',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmXSBbFHKAu9eYjhpqZdugWGEgy4j2DeD5AJbK3uPvwArK',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmTDJ48ECcMV8va1CWSjhhqzD7vVdsDMweqVLfukjQDMeQ', 'tags': [],
            },
            {
                'id': 195042, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'Tua Tempestade',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmNsxddw4A9QqwxppQKaBqBNUkAha3kg8rG4tgESjFAT4w',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmaSsNYYbWFgKwvxF3LqR8YzJ4zCKDKjKyBfcaNBYgMrBU', 'tags': [],
            },
            {
                'id': 195568, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'Fierce and Fabulosa - work in process',
                'src': 'https://dweb.link/ipfs/QmVknbTerGiHF3T4wFsXWFRAQWr1eWMmXFC4TUnCV974CB',
                'mimeType': 'audio/wav',
                'displayUri': 'ipfs://QmZQmmNEY1jG1xdqvy5Z3udwGRrRRfeZ7wZWZkWYNF6XDZ', 'tags': [],
            },
            {
                'id': 199974, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'STE-002[undefined].mp3 - 1hz estúdio',
                'src': 'https://infura-ipfs.io/ipfs/QmeeD6f1dUvLio7Hn49DuRVMJgo8L867ACXvr9rufQsD9Y',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmVKNQxqmi2s9E4TbmRjVu7FB5aL5PGcQZ2BibvV3mii8F', 'tags': [],
            },
            {
                'id': 200478, 'creator': {
                    'walletAddress': 'tz1Z54DwbANhFxaGsxLutmcFR57YeYHZ6ua3', 'name': 'nomadelabel',
                    'metadata': {'description': 'Nomade Tokens ensembles Trans-disciplinary arts, from bangkok to Irará. No gender or genre definitions'},
                }, 'title': 'Pire(กองฟืน) - pradit-saengkrai(thailand)',
                'src': 'https://cloudflare-ipfs.com/ipfs/QmU292s8BdY1Mr16T1bQEbSYqoUcWXg5sWsiZVrYc78CPw',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmRzpk3hFBZQfzzm2YYBowxdvDzrHfkTVkvGRrRFRzTKFu', 'tags': [],
            }],
    },
    {
        name: 'We love Marcello, dead or not',
        curator: '@hen_radio',
        description: 'Agreeable sound experiments',
        img: '/images/dead_marcello.png',
        slug: 'we-love-marcello-dead-or-not',
        tracks: [
            {
                'id': 162790, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'Krell Phrygian G',
                'src': 'https://ipfs.io/ipfs/QmXfnkWRwuTE5UbK6FAXfLR1BAiU93SeMo7qEcFoVzHDGE',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmRXXRdwAyjCNBKxZr3HDMKJLEVFjUjtPTbYrMz9PUBQwE', 'tags': [],
            },
            {
                'id': 178113, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'Machines by Alan Turing',
                'src': 'https://dweb.link/ipfs/QmepYpPzTsqNeArvSydhqDbWE3TZ6RsGV54hWMCGS6zqQD',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://Qmbbntf1xKKiTkhWBncDYmuHwK3i1sTEbeaAgsP1fVAL6g', 'tags': [],
            },
            {
                'id': 189702, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'morning path 5',
                'src': 'https://gateway.pinata.cloud/ipfs/QmZ4Txv4jHsekCpdC7V7fiEpFMFgSCCqNJPrYgFYUwNoJ6',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmeGnUqLXyaDJ5R75ZjQNfyrBdPBgF9xXhEaun4WY9PsyA', 'tags': [],
            },
            {
                'id': 197596, 'creator': {
                    'walletAddress': 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', 'name': 'dead_marcelo',
                    'metadata': {'description': '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, 'title': 'ao Sol',
                'src': 'https://dweb.link/ipfs/QmNaoRpbfzZGGwjDdE3VYj9UVne8a47Mj3tabGq5QuNZ9K',
                'mimeType': 'audio/mpeg',
                'displayUri': 'ipfs://QmQVoWd1Rhm4AwstTmZEZrEbV9eYd5nT5dpT29QbZGZmUg', 'tags': [],
            }],
    },
    {
        name: 'Tezos-Artcast Mix Tape #1',
        curator: '@ArtcastTezos',
        description: 'Tezos-artcast mixtape A: Sonic explorations in a time of strangeness.',
        img: '/images/tezos-artcast-mix-tape-1.png',
        slug: 'tezos-artcast-mix-tape-1',
        tracks: [
            {
                id: 40382, creator: {
                    walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX', name: '',
                    metadata: {},
                }, title: 'The Portal',
                src: 'https://dweb.link/ipfs/QmWRJpiSnDcu76NvUq9CkY1U2cVaP8Z75G3nArnqbQ1eGa',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmcisSaejao4ii7K4BtrZSGPCnN7tDZSW3Et7yrcdWRPjb', tags: [],
            },
            {
                id: 43421, creator: {
                    walletAddress: 'tz1YvJvemXC2tGoHNMizpJTLpMDsUrKbhwVY', name: 'DREAMZ',
                    metadata: {description: ''},
                }, title: 'The Official Hic et nunc Song (full version) ',
                src: 'https://dweb.link/ipfs/QmPBtLgYtAkKYg6C1vv8wUWFM5R6Eza2TNa7nyPbjWAQGM',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://Qme3r93omWizSM9Qa4Du1fAfJxK624nTwFd575pKLQx4Q7', tags: [],
            },
            {
                id: 44528, creator: {
                    walletAddress: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp', name: '',
                    metadata: {},
                }, title: '|WOAH}C00L|',
                src: 'https://cloudflare-ipfs.com/ipfs/QmYRADeeCDWyayLm8jrePE7EzVo9NXTBgXSfpshQcMuCEm',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmbE6CEphzZhPhm2sm5WPhEqGdunZTnvo4HP1NLQSrP2Wh', tags: [],
            },
            {
                id: 160691, creator: {
                    walletAddress: 'tz1h8HEENKv32TSzTzS52STTZGrE2q7rnrDL',
                    name: 'luisoalquimista', metadata: {description: 'Alchemy of the sound.'},
                }, title: 'Maracá Power',
                src: 'https://gateway.pinata.cloud/ipfs/Qmd1GkL2v5y9NVUJKnN6iEnuY3WG7AoYzrFHL959qHTLtT',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmZA3pKKSmdm9afDms91rZyZeQmebpvkKyiAX7Z4gmFKoD', tags: [],
            },
            {
                id: 163778, creator: {
                    walletAddress: 'tz1irQgAEeS7BWGMAnidUv4Mq5QWis18q2qe', name: '',
                    metadata: {},
                }, title: 'Fuck La Rat Race (Limited Sketch Edition)',
                src: 'https://dweb.link/ipfs/QmU1wYCvyGa1Y7Fyf4bKUs8GumQLQbCoMQfZi96sthe194',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmYEf63DsPV8r3oTikLzPrLnWzfhvYYV51GnCUV9SgUZYR', tags: [],
            },
            {
                id: 164362, creator: {
                    walletAddress: 'tz1hnmpvKPDDnXfh9tkE2ouWG2rP3uaUVjC4', name: '',
                    metadata: {},
                }, title: 'Yars Rev (full song)',
                src: 'https://cloudflare-ipfs.com/ipfs/QmfEejtbBJfB5uvm82Epd4oAbfriFR5G3kuo4wBe32qeBN',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmYugWTXubAhCetQEcvZr6eBJc2Ntw1RZ3D4rEDr9dno6F', tags: [],
            },
            {
                id: 170082, creator: {
                    walletAddress: 'tz1QpFbzwU6XuiByAyL9Ny8EEWYs4VAfPJH2', name: '',
                    metadata: {},
                },
                title: '𝖉𝖎𝖌𝖎𝖙𝖆𝖑 𝖒𝖔𝖘𝖘 - 𝖂𝖊𝖑𝖈𝖔𝖒𝖊 𝖙𝖔 𝖙𝖍𝖊 𝕮𝖑𝖔𝖚𝖉 𝕮𝖎𝖙𝖞',
                src: 'https://dweb.link/ipfs/QmbGisy69VoLdec6d5YihxCZg42JURNnsjz52EnvM9nEro',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmaydxYS75aENSSmXBLa6hQ9eZwEsuCfEDqJkvV3XPjzvA', tags: [],
            },
            {
                id: 171608, creator: {
                    walletAddress: 'tz1ae2d1BJt7YUqaaec6Xenh3mBqS7VjSZtK', name: 'Yoeshi Labs',
                    metadata: {
                        identicon: 'ipfs://QmPddzzzfjDcxvZH6LmNDEBo8FYZQFSrNNA7fkf2m9m5jV',
                        description: 'Music - Art - Support',
                    },
                }, title: 'Pumpin\' - Yoeshi Labs Ft. Seb & SPP',
                src: 'https://infura-ipfs.io/ipfs/QmbFfWKYHVMULKLyiJ5v1rjXEPqw1vMJdgsGeC2DJR6QqY',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmR5yn7dRGYNYp5ytsa6xmyvSqEScYtgE7mvYisCcjWbys', tags: [],
            },
            {
                id: 175354, creator: {
                    walletAddress: 'tz1TG9d5ACUTVsyASTP2yi412VbW8hf2HUV6', name: 'dead_marcelo',
                    metadata: {description: '#nft #modular #music on #web3 https://🎛🎧👽.y.at'},
                }, title: 'weaving webꜩ hen200',
                src: 'https://cloudflare-ipfs.com/ipfs/QmW6nNEFyodikvGVoZPzPGQVvefnwXm4W9ongmF5cmxikn',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmUrJdRc4Xecf6nFGg5cRqLP5VcNoGDqQYTa3KwLP27Zpx', tags: [],
            },
            {
                id: 176366, creator: {
                    walletAddress: 'tz1h5hcKNHceWHkezg9DjXqxBDXhDWn1EYjR', name: 'ABroJo Music',
                    metadata: {
                        identicon: 'ipfs://QmeF5wd4mLQQrVu5zp22X4ZLv4zZ4A8KcKQz42GULeynMo',
                        description: 'is Pablo Bersier\'s solo musical project. Electronic music producer for 25 years from Patagonia.',
                    },
                }, title: 'Dawn on Titan',
                src: 'https://dweb.link/ipfs/QmeWGwK7nV12kX12CQT3pD2tKqjxFbWYitcmJudj9EH74w',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmZnJoq7uhqFgQfoYrdEF73G3MwwGvEqGJQBv91tRY4n9G', tags: [],
            },
            {
                id: 176431, creator: {
                    walletAddress: 'tz2GP2o3kMJ8Q22FdjBo6QeheqUTAyEkHBo4', name: 'Marc Fendel',
                    metadata: {description: ''},
                }, title: 'Circular Data Remix',
                src: 'https://cloudflare-ipfs.com/ipfs/QmeqZza3NKH1STaes5934Hssru5uBvPpwHzhfvYVRpk4is',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmUSvwetYPTX6w9bfx26qMkP6bE6LBo4zZsbkw7dEyipGa', tags: [],
            },
            {
                id: 176756, creator: {
                    walletAddress: 'tz2DurpCmTtZp7YPHmP2hPyonZ3G6VMxqWSQ', name: 'Nujonakihs',
                    metadata: {description: 'Life is Art!? Will the values taught by a tribe from the future, where anything goes, make us happier in our everyday lives? Or not?'},
                }, title: 'O.D #721',
                src: 'https://dweb.link/ipfs/QmR8azpX7EPQqtw9YL8cFd9AFZEbggrm93tgaYxSCGnK1t',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmadMcsEV45Yn3Qty1a9FBp6QutyS98yzssSAWbCbFBNWG', tags: [],
            },
            {
                id: 177341, creator: {
                    walletAddress: 'tz1djJnb5WZx2ypYtqp2UZCVue6TrAd7M2MV', name: 'mentitaDAO',
                    metadata: {description: '❋ collective space in cryptoart of latinamerican artists ❋ promoting arts and circulation of knowledge ･:･゜ﾟ･*☆'},
                }, title: 'Electroplankton',
                src: 'https://ipfs.io/ipfs/QmPZbbGX6L5EF6ePjRX3XpnSvR7NWAcThqn3GJBpBdPLE',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmUrVqPkGcya2vju2wQ7worPnV9yxBaw88gwU5X3yCMcen', tags: [],
            },
            {
                id: 177343, creator: {
                    walletAddress: 'tz1fv8SRiTy7zJRbPJk4ZCc8CtUPzS6LVZPn', name: '',
                    metadata: {},
                }, title: '03 - YELMA (Perfume)',
                src: 'https://dweb.link/ipfs/QmPTDZ9Mi3vhAufTiVwKfVafdZWSvae2c4P8PWynx3xiBA',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmboMVS38mnkC4snkUZbTfdvUuWk2fXrqMrErcqRBpY3Wr', tags: [],
            },
            {
                id: 180023, creator: {
                    walletAddress: 'tz1R7Canwm9D8uvSQfgeibKuAqEekfzYwvai',
                    name: 'GinoFinOcchio', metadata: {
                        identicon: 'ipfs://QmTNgUHk9DR6QpFTycdaKjTDyBmtpAyX54WSRAt17oActL',
                        description: '',
                    },
                }, title: 'ICE787',
                src: 'https://ipfs.io/ipfs/QmdKkZp3zpmB1HojsvLx2sEazxEUsgt7REKmdgENv4mnjZ',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmSXm2XpqfJG4fhv9LeuPZZqhCd2inaAR4CqrSMBhyAc1i', tags: [],
            },
            {
                id: 184521, creator: {
                    walletAddress: 'tz1RWCDAjTJXfQUy99tuL6n1cdj9gnyRzXCt', name: 'yuleaureh',
                    metadata: {
                        identicon: 'ipfs://QmeNLm38exWTFPdZgBkgn87dqEpt37XnwECWsqd1arJJfK',
                        description: 'Visual artist and Musician from Brazil. | Coletivo Arruaça | Sampleada Label www.sampleada.com',
                    },
                }, title: 'Fragmentos vol.1',
                src: 'https://gateway.pinata.cloud/ipfs/QmRUDkAgaEWH2aSeySdwaJT54gYsgFTdCpHXZj8uKTiXxu',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmU1pF6jpGDy6AumhtFD4DPnaQRPyutkK7HTGo4ebnaHc6', tags: [],
            },
            {
                id: 184534, creator: {
                    walletAddress: 'tz1YNGWkQTyNvEvuukFhLehZv7niyAdmuWEp', name: '',
                    metadata: {},
                }, title: 'Catinga',
                src: 'https://gateway.pinata.cloud/ipfs/QmV8QUfPREXUaqr5cT3XiZY9y4NGaDg9uKWxvLDHVnXjyJ',
                mimeType: 'audio/wav',
                displayUri: 'ipfs://QmZviymv41K61fG3qzqGzvGnZA7Aw7FL7Z2Hx7Df6cVhVN', tags: [],
            },
            {
                id: 185156, creator: {
                    walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S', name: 'Bface',
                    metadata: {description: 'Beats, Design & life'},
                }, title: 'Test Press #2: Flippn Rock',
                src: 'https://dweb.link/ipfs/QmXGNGVHtTFgGZHuAqAk5gvzcPiWHrU6ju2WShrLEXMGDc',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmQy5btPKY9fCmjfhGatbADpFxWaVqct3EAvTZAtH5oKJt', tags: [],
            },
            {
                id: 187125, creator: {
                    walletAddress: 'tz1LsnZE1fbmc5R42QqV7VDqFt9NV8MZ7tmk',
                    name: 'fractalvector',
                    metadata: {description: 'Pedro Kozovits - Musician / Code Artist / Math enthusiast'},
                }, title: 'Analog Journey - Rage Against Humanity',
                src: 'https://cloudflare-ipfs.com/ipfs/QmasbbhzTcvSyKCyE4LXpgNx6rMmsaTL7TMcq9VezQb8f6',
                mimeType: 'audio/mpeg',
                displayUri: 'ipfs://QmStLusSuCtm1JQBWYXTAHJbqSPaU5PYfJxaqBC31y6sRo', tags: [],
            }],

    },
    {
        name: 'Hicathon Dev',
        curator: 'HEN Radio',
        description: 'The tracks that made hen.radio, listened to on repeat for hackday development',
        img: '/images/playlist_cover_0.png',
        slug: 'hicathon-dev',
        tracks: [
            {
                id: 48594,
                title: 'A l\'Ouest',
                src: 'https://ipfs.io/ipfs/QmawLCNM666CsHajN7MfJH9baWq2JRshxXX7QETL9dR4NA',
                mimeType: 'audio/ogg',
                creator: {walletAddress: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f'},
                tags: [],
            },
            {
                id: 44540,
                title: 'BUDS',
                src: 'https://ipfs.io/ipfs/QmaRtMtfQEbUEj39gwCSNzcLPhBaTEnTXsFjWjeXNPMe3c',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp'},
                tags: [],
            },
            {
                id: 16396,
                title: 'The Air That Never Was',
                src: 'https://ipfs.io/ipfs/QmXpvmA6R4nJmeZsDXJY2EyUeYcM5iCg2Ww1jtjTnrf5iQ',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1YJvMiZyXnzvV9pxtAiuCFvaG7XoBZhbUQ'},
                tags: [],
            },
            {
                id: 5302,
                title: 'Dub Stars',
                src: 'https://ipfs.io/ipfs/Qmd8vTe22AdcYV84hTD2UEZFDicZZNf4j9bUBfDQsidy11',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f'},
                tags: [],
            },
            {
                id: 41309,
                title: 'Improvisation for Melody Owen',
                src: 'https://ipfs.io/ipfs/QmXLBb1b5c3hA3Rsccs19Zw9PCQEuJiU3drAyfFnTa2ZSP',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1YJvMiZyXnzvV9pxtAiuCFvaG7XoBZhbUQ'},
                tags: [],
            },
            {
                id: 5298,
                title: 'Melancome',
                src: 'https://ipfs.io/ipfs/QmNNrraeevcUhDT4saUA6W1AqiukZvvyRtroCf57PhjjyV',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f'},
                tags: [],
            },
            {
                id: 44528,
                title: '|WOAH}C00L|',
                src: 'https://ipfs.io/ipfs/QmYRADeeCDWyayLm8jrePE7EzVo9NXTBgXSfpshQcMuCEm',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp'},
                tags: [],
            },
        ],
    },
    {
        name: 'Eclectic Coups de Coeur #1',
        curator: 'Lauzaki',
        description: 'A mixed bag of HEN gems',
        img: '/images/playlist_cover_1.jpg',
        slug: 'eclectic-coups-de-coeur-1',
        tracks: [
            {
                id: 17575,
                title: 'Dancing Bones',
                src: 'https://ipfs.io/ipfs/QmNot4YVcRqByEiiNHKwocR1Ncnab9VGdHtUbLKD5Q14bT',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1VQwSyQPA1owaqZ2RUkDEKsdZsfQPVvVbN'},
                tags: [],
            },
            {
                id: 11305,
                title: 'rumpy wants a baby',
                src: 'https://ipfs.io/ipfs/QmUfPW1eBdD7naLGopdpJyXYTezpU46Bkam9d2kx96JoFg',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ZQ3RF4Qk2P9qau3ya4hKMxqq42SEjhbYw'},
                tags: [],
            },
            {
                id: 97695,
                title: 'PEACE',
                src: 'https://ipfs.io/ipfs/QmVX35MDiPpsXW3gtKumNL2j44ZzWr5QPZP5vbgHDE5VoE',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1Uj8B2iVVcVV7FHmFL7PTZdNK4onhXP1Bs'},
                tags: [],
            },
            {
                id: 97684,
                title: 'SUNDAYSUSET',
                src: 'https://ipfs.io/ipfs/QmdmgwMFxarbpEk1eZzUm2JEiBg9VGoLmBphyUDrSbwU4w',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1Uj8B2iVVcVV7FHmFL7PTZdNK4onhXP1Bs'},
                tags: [],
            },
            {
                id: 101079,
                title: 'Crypto Noise series #04',
                src: 'https://ipfs.io/ipfs/QmatzMuSP2XAWDMpjUxmXeFDCSJAtePjhte7J58DE4ssKp',
                mimeType: 'audio/wav',
                creator: {walletAddress: 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC'},
                tags: [],
            },
            {
                id: 9482,
                title: 'gpp udah makan by bagvs',
                src: 'https://ipfs.io/ipfs/QmaJLxXppTPvLJjLFCpntAPT5TwaShxeGEqnFTP6AborBt',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1PTddXFRZDHnzy8k34XiKwy7p2vabY8Qxo'},
                tags: [],
            },
            {
                id: 12095,
                title: 'Malachi Basden and Wes Anderson -- I Can\'t Get Started',
                src: 'https://ipfs.io/ipfs/Qmdq5oLpi5gWPk4QsJ3HcJuAusNr2bV7L1EBHddJYDByUd',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1Z7PUrxjaev1EM2SeGtetiZgZedrYvgFmY'},
                tags: [],
            },
            {
                id: 43386,
                title: 'continuum_after_latency',
                src: 'https://ipfs.io/ipfs/Qmb92ifujVsctJL5R8X25prWjNjjuDCWScysEXiAZSrD2v',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz2MR9zog3QaSKRMsxMRqYtDevwoRKVvMQX7'},
                tags: [],
            },
        ],
    },
    {
        name: 'Ambient Atmosphere',
        curator: 'HEN Radio',
        description: 'Ambient Future Atmosphere',
        img: '/images/playlist_cover_2.png',
        slug: 'ambient-atmosphere',
        tracks: [
            {
                id: 8577,
                title: 'Geometrical Psychology #8',
                src: 'https://ipfs.io/ipfs/QmfHLRCnhFY5oBsmE9gKH6xjFUpbjNcqRG8XKTm52jaiHa',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1TA2GsoJmC6G57DZfMw9cj5Z8ztviGBzU7'},
                tags: [],
            },
            {
                id: 6337,
                title: 'Eurorack ambient jam #1',
                src: 'https://ipfs.io/ipfs/QmUmhLsTPKRjwJN3eNfYAJ9Hw1SaRbC8gQTky9MBPfWcr1',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1etmVTu5kPrSZjQPNF2nE79xyKddjwguyz'},
                tags: [],
            },
            {
                id: 10045,
                title: 'Eurorack ambient jam #4',
                src: 'https://ipfs.io/ipfs/QmVdoqKAQNQNJ8YBGTk6pXsrXNZqvErHNzxKFg7cnPn9xj',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1etmVTu5kPrSZjQPNF2nE79xyKddjwguyz'},
                tags: [],
            },
        ],
    },
    {
        name: 'Experimental Brazil',
        curator: 'HEN Radio',
        description: 'Experimental Brazil',
        img: '/images/playlist_cover_3.png',
        slug: 'experimental-brazil',
        tracks: [
            {
                id: 44945,
                title: 'Bface - Touch Ya!',
                src: 'https://ipfs.io/ipfs/Qmf9BCvmWyTwXjFiyTTswRehfSmBF2JPowYutDH1um4akG',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S'},
                tags: [],
            },
            {
                id: 45003,
                title: 'Bface - 70skrl',
                src: 'https://ipfs.io/ipfs/QmaWPAQjpotsgbv66aECT2SbbSXKDhjF9FxGrozVP2DYyn',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S'},
                tags: [],
            },
            {
                id: 44984,
                title: 'Bface - Vida Severina',
                src: 'https://ipfs.io/ipfs/QmQJ86BBKZKmoM8bJDSZ2AohKeWv1atP21CrudQhukfU8D',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S'},
                tags: [],
            },
        ],
    },
    {
        name: 'House',
        curator: 'HEN Radio',
        description: 'House on the soft side',
        img: '/images/playlist_cover_4.png',
        slug: 'house',
        tracks: [
            {
                id: 56836,
                title: 'Walking Home',
                src: 'https://ipfs.io/ipfs/QmatrNGiVEo5RjNkV27CS2WgwhQkN7i4xN7azLrUewycXB',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
            {
                id: 52492,
                title: 'Stronger (Yeti Tears Remix)',
                src: 'https://ipfs.io/ipfs/QmWHAQEhYuWka4hXx5MQx773tW8ZY76rdJ2io6VfrFECnV',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'ttz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
            {
                id: 40382,
                title: 'The Portal',
                src: 'https://ipfs.io/ipfs/QmWRJpiSnDcu76NvUq9CkY1U2cVaP8Z75G3nArnqbQ1eGa',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
            {
                id: 35832,
                title: 'Aerophobia',
                src: 'https://ipfs.io/ipfs/QmekqLeahzokRF8S6PoRUj6mvXn3xJWErr6oMePkq8pQUX',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX'},
                tags: [],
            },
        ],
    },
    {
        name: 'Cryptobeat',
        curator: 'HEN Radio',
        description: 'Cryptobeat glitch',
        img: '/images/playlist_cover_7.png',
        slug: 'cryptobeat',
        tracks: [
            {
                id: 58421,
                title: 'CIRCLE COMPLETE (production GLASSY)',
                src: 'https://ipfs.io/ipfs/QmUVqJPzx9v6WDeWVxxVSe1PrMyibyWtFnioAR7sY42tyG',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'ttz1ZtxSzCJkDNztv2QRP8xgVLafxv9D5aYea'},
                tags: [],
            },
            {
                id: 39331,
                title: 'CANNABIS SAINTS BEAT TAPE [Song 1 Glory and Time]',
                src: 'https://ipfs.io/ipfs/QmVRU7oG6RnJ6dQ1QAUm1Doji2Nfu2cuuCVmBjYNtrHahq',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1ZtxSzCJkDNztv2QRP8xgVLafxv9D5aYea'},
                tags: [],
            },
        ],
    },
    {
        name: 'Trance',
        curator: 'HEN Radio',
        description: 'Psychedelic Trance',
        img: '/images/playlist_cover_5.png',
        slug: 'trance',
        tracks: [
            {
                id: 34506,
                title: 'Poliwog - UNR Work In Progress',
                src: 'https://ipfs.io/ipfs/Qmc7rFFKmUzasjej9y3tkjc1kwrWQPjPWdK2gNdFFymdbu',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1MUcbDL1UbE4DTibDuDs8dLnih4u6Ka8uT'},
                tags: [],
            },
            {
                id: 77720,
                title: 'Unreleased Psychedelic Trance Track 2 by Poliwog',
                src: 'https://ipfs.io/ipfs/QmQpPXELuT88xHpKo7FF4F68pv2vDe7txkXMDYo6fH3nQ7',
                mimeType: 'audio/mpeg',
                creator: {walletAddress: 'tz1MUcbDL1UbE4DTibDuDs8dLnih4u6Ka8uT'},
                tags: [],
            },
        ],
    },
];
